### ISSUE TITLE
Work on scheduled upgrades to wholebodydynamics device

### ISSUE THREAD

**Issue by fjandrad** [robotology/whole-body-estimators#41]
Following the [transfer of wholebodydynamics device into this repo](https://github.com/robotology/whole-body-estimators/pull/16) and its incoming inclusion in [robotology-superbuild](https://github.com/robotology/robotology-superbuild/issues/365) we need to add the work scheduled for it in this repo.

The scheduled changes to wholebodydynamics device were:

- [x] Add support for compensating temperature in Force/Torque sensors readings and for specify user offline offset. ([legacy PR](https://github.com/robotology/codyco-modules/pull/281) and recent PR #45). 
- [x] Add the option to select the type of the Wrench Contact (full-wrench, pure-force, pure-force-with-known-direction) #17 
- [x] Handle CMake deprecation warnings #58
- [x] Release 0.2.0 that includes wholebodydynamics #43  
- [x] Add Github actions #6 
- [x] Add Github labels
- ~[ ] Refactor the device by splitting to improve readability.~

**Comment by HosameldinMohamed** [comment]
>  Refactor the device by splitting to improve readability.

We can remove this from this Epic and make it into a separate Epic, since the complexity of the task is higher.

**Comment by prashanthr05** [comment]
> We can remove this from this Epic and make it into a separate Epic, since the complexity of the task is higher.

An issue already exists, actually. https://github.com/dic-iit/component_wholebody-teleoperation/issues/241. We could convert it into an epic.

**Comment by prashanthr05** [comment]
@HosameldinMohamed shall we close this epic?

**Comment by HosameldinMohamed** [comment]
@prashanthr05 
It seems that this is remaining.

> - [ ]  Handle CMake deprecation warnings

I'll open a new issue to continue your work in https://github.com/robotology/whole-body-estimators/pull/58#issuecomment-608299759

**Comment by HosameldinMohamed** [comment]
> @prashanthr05
> It seems that this is remaining.
> 
>  Handle CMake deprecation warnings
> I'll open a new issue to continue your work in #58 (comment)

I opened #85, however the remaining deprecation warnings are not specifically related to `wholeBodyDynamics`. So I guess we don't have to connect it to this epic and we can close the epic.

**Comment by prashanthr05** [comment]
@HosameldinMohamed thanks for opening the issue. Let's close the epic after addressing that issue.
I added that issue to this epic.

**Comment by prashanthr05** [comment]
Thanks for all the upgrades @fjandrad @HosameldinMohamed @traversaro 

We can finally close this epic.
